### ISSUE TITLE
Update process for IBAN registry data

### ISSUE THREAD

**Issue by matid** [gocardless/ibandit#176]
Hi GoCardless! 👋 

I noticed that your IBAN registry is out of date and wanted to get it updated.

It’s missing 8 countries from the most-recent registry published by SWIFT [here](https://www.swift.com/resource/iban-registry-pdf).

The `.txt` version available for download looks different than what’s in `data/raw/IBAN_Registry.txt`. I’m not sure if the format has changed, or you’re using a different source?

The countries that are missing are `BY`, `EG`, `FO`, `IQ`, `LC`, `SC`, `UA` and `VA`.

I was going to add them in by hand, but I figured that there’s a different update process that should be followed since the `structures.yml` file is generated by a rake task.

Any pointers for how I’d go about getting the data set refreshed?

**Comment by JoeSouthan** [comment]
Hi @matid,

Thanks for bringing this up and apologies for getting back late. 

It looks like swift have changed the format of the registry txt file which I have taken into account for #195. The rake task will only get you so far unfortunately as the registry file that swift provides has errors. In general you'd add the example ibans to the spec and correct the `structures.yml` until it passes.
