### ISSUE TITLE
Random strings can lead to crashes

### ISSUE THREAD

**Issue by frane** [gocardless/ibandit#71]
Hi,

Using random strings like "dezzzz" causes Ibandit to crash.

`Ibandit::IBAN.new("dezzzz")` leads to `NoMethodError (undefined method `[]' for nil:NilClass)`

I traced the error down to:
```
gems/ibandit-0.11.1/lib/ibandit/local_details_cleaner.rb:4clean	
module Ibandit
  module LocalDetailsCleaner
    def self.clean(local_details)
      country_code = local_details[:country_code]  <<< NoMethodError (undefined method `[]' for nil:NilClass)
      if can_clean?(country_code, local_details)
        local_details = local_details.merge(
```

It seems that because of the 'zz' in the positions 3-4 of the string, it is wrongly assumed to be a pseudo IBAN. `Ibandit::IBAN.new("de12zz")` work without crashing.

Regards,
Frane

**Comment by greysteil** [comment]
Thanks for the heads up. Fixed in 0.11.2.
